// This file is "main.dart"
import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:flutter/foundation.dart';

// required: associates our `main.dart` with the code generated by Freezed
part 'calendar_state.freezed.dart';
// optional: Since our Person class is serializable, we must add this line.
// But if Person was not serializable, we could skip it.

@freezed
class CalendarState with _$CalendarState {
  const factory CalendarState({
    required int month,
    required int year,
   required int swipeIndex,
    DateTime? selectedDateTime,
  }) = _CalendarState;
}
